"""Update PageView model with path and relationships

Revision ID: afc23bbb572e
Revises: 5b4109bd61e2
Create Date: 2024-11-30 23:53:57.314465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc23bbb572e'
down_revision = '5b4109bd61e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_agent',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.drop_column('referrer')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('referrer', sa.VARCHAR(length=255), nullable=True))
        batch_op.alter_column('user_agent',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('path')

    # ### end Alembic commands ###
