"""Add backup schedule model

Revision ID: c567b3bea632
Revises: 1d7d196fd4d8
Create Date: 2024-11-30 23:35:45.350996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c567b3bea632'
down_revision = '1d7d196fd4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backup_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=5), nullable=True),
    sa.Column('retention', sa.Integer(), nullable=True),
    sa.Column('notify_on_failure', sa.Boolean(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))

    op.drop_table('backup_schedule')
    # ### end Alembic commands ###
