"""Update PageView model relationships

Revision ID: f622ce7cb309
Revises: 7713f24f6704
Create Date: 2024-12-04 21:38:05.694452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f622ce7cb309'
down_revision = '7713f24f6704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_pageview_post', 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('page_views', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pageview_post', type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
